### ISSUE TITLE
Replace deprecated instances of DeterministicEpiModel with MatrixEpiModel

### ISSUE THREAD

**Issue by edwenger** [benmaier/epipack#21]
e.g. in [epipack_SIRS_example.ipynb](https://github.com/benmaier/epipack/blob/master/cookbook/notebooks/epipack_SIRS_example.ipynb) cookbook example:
`from epipack import SymbolicEpiModel, DeterministicEpiModel, StochasticEpiModel
`

(awesome package btw!)

**Comment by benmaier** [comment]
Ah, right, thanks for pointing that out, will get to it! Sorry for getting back to you so late, took some time off.
